### ISSUE TITLE
Put brackets around macro args

### ISSUE THREAD

**Issue by geraintwhite** [olls/maze-interpreter-v3#1]
Macro args should be in brackets in the macro body to prevent the following happening:

``` c
#define COORD(y, x) (y * 100 + x)
COORD(x + 1, 3) # => x + 1 * 100 + 3

#define COORD(y, x) ((y) * 100 + (x))
COORD(x + 1, 3) # => (x + 1) * 100 + (3)
```

See here https://gcc.gnu.org/onlinedocs/cpp/Macro-Arguments.html

**Comment by olls** [comment]
Did I remove them?

**Comment by olls** [comment]
Oh, good point. I didn't read it properly the first time.
